import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('settings import export copy', () => {
  it('shows backup and migration sections without legacy csv/json export copy', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')
    const backupModal = readFileSync('src/components/SubtrackerBackupModal.vue', 'utf8')

    expect(source).toContain("t('settings.sections.importExport')")
    expect(source).toContain("t('settings.sections.backup')")
    expect(source).toContain("t('settings.sections.migration')")
    expect(source).toContain("t('settings.buttons.exportBackup')")
    expect(source).toContain("t('settings.buttons.restoreBackup')")
    expect(source).toContain("t('settings.buttons.importWallos')")
    expect(source).toContain("t('settings.helps.backup')")
    expect(source).toContain("t('settings.helps.migration')")
    expect(source).toContain("t('settings.helps.workerRuntime')")
    expect(source).toContain("t('settings.helps.workerRuntimeR2Enabled')")
    expect(source).toContain("t('settings.helps.workerRuntimeR2Disabled')")
    expect(source).toContain("t('settings.helps.notificationSettingsWorkerLite')")
    expect(source).toContain("settingsForm.storageCapabilities.runtime === 'worker-lite'")
    expect(source).toContain('isWorkerLiteRuntime')
    expect(source).toContain('normalizeWorkerEmailProvider')
    expect(source).toContain(":disabled=\"isWorkerLiteRuntime\"")
    expect(source).toContain('settingsForm.storageCapabilities.r2Enabled')
    expect(source).toContain("t('settings.about.liteBranch')")
    expect(source).toContain('https://github.com/Smile-QWQ/SubTracker/tree/lite')
    expect(source).toContain('showSubtrackerBackupModal')
    expect(source).toContain('showWallosImportModal')
    expect(source).not.toContain('导出 CSV')
    expect(source).not.toContain('导出 JSON')
    expect(source).not.toContain('支持通过 ZIP 进行导出和导入')
    expect(source).not.toContain('从第三方同类项目导入数据。')
    expect(backupModal).toContain('title="恢复备份"')
    expect(backupModal).not.toContain('title="导入 ZIP"')
    expect(backupModal).toContain('预览备份')
    expect(backupModal).toContain('确认恢复')
    expect(backupModal).toContain('恢复模式')
    expect(backupModal).toContain('恢复预览')
    expect(backupModal).toContain('备份 ZIP 无法解析')
    expect(backupModal).toContain('未导入任何新数据，重复项已自动跳过')
    expect(backupModal).toContain('按备份中的唯一标识（CUID）幂等跳过')
    expect(backupModal).toContain('现有同唯一标识（CUID）订阅')
    expect(backupModal).toContain('现有同唯一标识（CUID）支付记录')
    expect(backupModal).not.toContain('生成预览')
    expect(backupModal).not.toContain('确认导入')
  })

  it('expands ai settings wording from recognition-only to shared ai capability', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')

    expect(source).toContain("t('settings.sections.ai')")
    expect(source).toContain("t('settings.labels.enableAi')")
    expect(source).toContain("t('settings.labels.aiSummary')")
    expect(source).toContain("t('settings.helps.aiSettings')")
    expect(source).toContain("t('settings.labels.customRecognitionPrompt')")
    expect(source).toContain("t('settings.labels.customSummaryPrompt')")
    expect(source).not.toContain('title="AI 识别设置"')
    expect(source).not.toContain('启用 AI 识别')
  })

  it('adds forgot password toggle under credentials with direct-channel guard', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')

    expect(source).toContain("t('settings.labels.enableForgotPassword')")
    expect(source).toContain('forgotPasswordToggleUnlocked')
    expect(source).toContain('handleForgotPasswordToggleChange')
    expect(source).toContain("t('settings.messages.forgotPasswordEnabled')")
    expect(source).toContain("t('settings.messages.forgotPasswordDisabled')")
    expect(source).toContain("t('settings.sections.credentials')")
    expect(source).toContain("t('settings.sections.about')")
    expect(source).toContain("t('settings.sections.credits')")
    expect(source).toContain('aboutEntries')
    expect(source).toContain('creditEntries')
  })
})
