import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('settings import export copy', () => {
  it('shows backup and migration sections without legacy csv/json export copy', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')
    const backupModal = readFileSync('src/components/SubtrackerBackupModal.vue', 'utf8')

    expect(source).toContain("t('settings.sections.importExport')")
    expect(source).toContain("t('settings.sections.backup')")
    expect(source).toContain("t('settings.sections.migration')")
    expect(source).toContain("t('settings.buttons.exportBackup')")
    expect(source).toContain("t('settings.buttons.restoreBackup')")
    expect(source).toContain("t('settings.buttons.importWallos')")
    expect(source).toContain("t('settings.helps.backup')")
    expect(source).toContain("t('settings.helps.migration')")
    expect(source).toContain("t('settings.helps.workerRuntime')")
    expect(source).toContain("t('settings.helps.workerRuntimeR2Enabled')")
    expect(source).toContain("t('settings.helps.workerRuntimeR2Disabled')")
    expect(source).toContain("t('settings.helps.notificationSettingsWorkerLite')")
    expect(source).toContain("settingsForm.storageCapabilities.runtime === 'worker-lite'")
    expect(source).toContain('isWorkerLiteRuntime')
    expect(source).toContain('normalizeWorkerEmailProvider')
    expect(source).toContain("t('settings.helps.smtpPortWorkerLite')")
    expect(source).toContain("t('settings.validation.smtpPort25Blocked')")
    expect(source).toContain('isWorkerLiteBlockedSmtpPort')
    expect(source).toContain('settingsForm.storageCapabilities.r2Enabled')
    expect(source).toContain("t('settings.about.liteBranch')")
    expect(source).toContain('https://github.com/Smile-QWQ/SubTracker/tree/lite')
    expect(source).toContain('showSubtrackerBackupModal')
    expect(source).toContain('showWallosImportModal')
    expect(source).not.toContain('导出 CSV')
    expect(source).not.toContain('导出 JSON')
    expect(source).not.toContain('支持通过 ZIP 进行导出和导入')
    expect(source).not.toContain('从第三方同类项目导入数据。')
    expect(backupModal).toContain("t('subscriptions.backupModal.title')")
    expect(backupModal).toContain("t('subscriptions.backupModal.previewBackup')")
    expect(backupModal).toContain("t('subscriptions.backupModal.confirmRestore')")
    expect(backupModal).toContain("t('subscriptions.backupModal.restoreMode')")
    expect(backupModal).toContain("t('subscriptions.backupModal.restorePreview')")
    expect(backupModal).toContain("t('subscriptions.backupModal.invalidZip')")
    expect(backupModal).toContain("t('subscriptions.backupModal.nothingImported')")
    expect(backupModal).toContain("t('subscriptions.backupModal.existingSubscriptions')")
    expect(backupModal).toContain("t('subscriptions.backupModal.existingPaymentRecords')")
    expect(backupModal).not.toContain('title="导入 ZIP"')
    expect(backupModal).not.toContain('生成预览')
    expect(backupModal).not.toContain('确认导入')
  })

  it('expands ai settings wording from recognition-only to shared ai capability', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')

    expect(source).toContain("t('settings.sections.ai')")
    expect(source).toContain("t('settings.labels.enableAi')")
    expect(source).toContain("t('settings.labels.aiSummary')")
    expect(source).toContain("t('settings.helps.aiSettings')")
    expect(source).toContain("t('settings.labels.customRecognitionPrompt')")
    expect(source).toContain("t('settings.labels.customSummaryPrompt')")
    expect(source).not.toContain('title="AI 识别设置"')
    expect(source).not.toContain('启用 AI 识别')
  })

  it('adds forgot password toggle under credentials with direct-channel guard', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')

    expect(source).toContain("t('settings.labels.enableForgotPassword')")
    expect(source).toContain('forgotPasswordToggleUnlocked')
    expect(source).toContain('handleForgotPasswordToggleChange')
    expect(source).toContain("t('settings.messages.forgotPasswordEnabled')")
    expect(source).toContain("t('settings.messages.forgotPasswordDisabled')")
    expect(source).toContain("t('settings.sections.credentials')")
    expect(source).toContain("t('settings.sections.about')")
    expect(source).toContain("t('settings.sections.credits')")
    expect(source).toContain('aboutEntries')
    expect(source).toContain('creditEntries')
  })

  it('keeps smtp and resend selectable in worker lite without forcing resend fallback', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')

    expect(source).toContain("t('settings.options.emailProvider.smtp')")
    expect(source).toContain("t('settings.options.emailProvider.resend')")
    expect(source).toContain("emailProvider: 'smtp'")
    expect(source).toContain('<n-select')
    expect(source).toContain('v-model:value="settingsForm.emailProvider"')
    expect(source).toContain(':options="emailProviderOptions"')
    expect(source).not.toContain("settingsForm.emailProvider = 'resend'")
  })
})
