import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('settings import export section', () => {
  it('uses neutral import/export wording for backup zip section', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')
    const backupModal = readFileSync('src/components/SubtrackerBackupModal.vue', 'utf8')

    expect(source).toContain('title="导入和导出"')
    expect(source).toContain('title="备份"')
    expect(source).toContain('title="迁移"')
    expect(source).toContain('导出备份')
    expect(source).toContain('恢复备份')
    expect(source).toContain('支持通过 ZIP 进行备份与恢复，包含订阅、标签、支付记录、排序、系统设置与本地 Logo')
    expect(source).toContain('从第三方同类项目导入数据')
    expect(source).toContain('导入 Wallos')
    expect(source).not.toContain('可在这里导入和导出数据。')
    expect(source).not.toContain('导出 CSV')
    expect(source).not.toContain('导出 JSON')
    expect(source).not.toContain('支持通过 ZIP 进行导出和导入')
    expect(source).not.toContain('从第三方同类项目导入数据。')
    expect(source).not.toContain('title="导入 Wallos"')
    expect(source).not.toContain('导出 ZIP')
    expect(source).not.toContain('导入 ZIP')
    expect(source).not.toContain('项目自身完整备份恢复')
    expect(source).not.toContain('业务完整恢复包')

    expect(backupModal).toContain('title="恢复备份"')
    expect(backupModal).toContain('预览备份')
    expect(backupModal).toContain('确认恢复')
    expect(backupModal).toContain('恢复模式')
    expect(backupModal).toContain('恢复预览')
    expect(backupModal).toContain('备份 ZIP 无法解析')
    expect(backupModal).toContain('未导入任何新数据，重复项已自动跳过')
    expect(backupModal).toContain('按备份中的唯一标识（CUID）幂等跳过')
    expect(backupModal).toContain('现有同唯一标识（CUID）订阅')
    expect(backupModal).toContain('现有同唯一标识（CUID）支付记录')
    expect(backupModal).not.toContain('title="导入 ZIP"')
    expect(backupModal).not.toContain('生成预览')
    expect(backupModal).not.toContain('确认导入')
  })

  it('expands ai settings wording from recognition-only to shared ai capability', () => {
    const source = readFileSync('src/pages/SettingsPage.vue', 'utf8')

    expect(source).toContain('title="AI 能力设置"')
    expect(source).toContain('启用 AI 能力')
    expect(source).toContain('AI 总结')
    expect(source).toContain('AI 能力总开关控制识别与连接测试；AI 总结可单独开启或关闭')
    expect(source).toContain('自定义识别提示词')
    expect(source).toContain('自定义总结提示词')
    expect(source).not.toContain('title="AI 识别设置"')
    expect(source).not.toContain('启用 AI 识别')
  })
})
