import { randomUUID } from 'node:crypto'
import {
  AppriseConfigSchema,
  type AppriseConfigInput,
  type AppriseSyncStatus,
  type AppriseTargetInput
} from '@subtracker/shared'

export const APPRISE_ENABLED_TARGET_TAG = 'st-enabled'
const APPRISE_TARGET_TAG_PREFIX = 'st-target-'

export function normalizeAppriseTag(value: string) {
  return String(value ?? '')
    .trim()
    .toLowerCase()
    .replace(/[\s,+|&]+/g, '-')
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)
}

export function normalizeAppriseTarget(target: AppriseTargetInput): AppriseTargetInput {
  return {
    id: String(target.id ?? '').trim(),
    name: String(target.name ?? '').trim(),
    url: String(target.url ?? '').trim(),
    enabled: Boolean(target.enabled)
  }
}

export function normalizeAppriseTargets(targets: AppriseTargetInput[]) {
  return targets.map((target) => normalizeAppriseTarget(target))
}

export function hasAppriseTargets(config: Pick<AppriseConfigInput, 'targets'>) {
  return (config.targets ?? []).length > 0
}

export function hasEnabledAppriseTargets(config: Pick<AppriseConfigInput, 'targets'>) {
  return (config.targets ?? []).some((target) => target.enabled)
}

export function getAppriseTargetInternalTag(targetId: string) {
  return `${APPRISE_TARGET_TAG_PREFIX}${normalizeAppriseTag(targetId)}`
}

export function buildAppriseConfigText(config: Pick<AppriseConfigInput, 'targets'>) {
  const lines = ['# Generated by SubTracker']

  for (const originalTarget of config.targets ?? []) {
    const target = normalizeAppriseTarget(originalTarget)
    if (!target.id || !target.name || !target.url) {
      continue
    }

    const tags = Array.from(
      new Set([
        getAppriseTargetInternalTag(target.id),
        ...(target.enabled ? [APPRISE_ENABLED_TARGET_TAG] : [])
      ])
    )
    lines.push(`${tags.join(',')}=${target.url}`)
  }

  return `${lines.join('\n')}\n`
}

export function withAppriseSyncState(
  config: AppriseConfigInput,
  state: {
    lastSyncStatus: AppriseSyncStatus
    lastSyncAt: string | null
    lastSyncError: string | null
  }
) {
  return AppriseConfigSchema.parse({
    ...config,
    lastSyncStatus: state.lastSyncStatus,
    lastSyncAt: state.lastSyncAt,
    lastSyncError: state.lastSyncError
  })
}

export function buildIdleAppriseSyncState() {
  return {
    lastSyncStatus: 'idle' as const,
    lastSyncAt: null,
    lastSyncError: null
  }
}

export function buildSuccessfulAppriseSyncState(now = new Date()) {
  return {
    lastSyncStatus: 'synced' as const,
    lastSyncAt: now.toISOString(),
    lastSyncError: null
  }
}

export function buildFailedAppriseSyncState(error: unknown, now = new Date()) {
  return {
    lastSyncStatus: 'failed' as const,
    lastSyncAt: now.toISOString(),
    lastSyncError: error instanceof Error ? error.message : String(error ?? 'unknown error')
  }
}

export function createAppriseTemporaryKey(baseKey: string) {
  const normalizedBase = String(baseKey ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')

  return `${normalizedBase || 'subtracker'}-test-${randomUUID()}`
}

